apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-notification
  template:
    metadata:
      labels:
        app: email-notification
    spec:
      containers:
      - name: email-notification
        image: 733318626765.dkr.ecr.us-east-1.amazonaws.com/notification/email-notification:latest
        ports:
        - containerPort: 5000
        env:
        - name: SENDER_EMAIL
          value: "bhavinbpalan90@gmail.com"
---
apiVersion: v1
kind: Service
metadata:
  name: email-notification-service
spec:
  selector:
    app: email-notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
